name: Deploy Babashka Uberscript

on:
  push:
    tags:
      - 'v*' # Run on tags starting with 'v'
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create uberscript with Babashka
        uses: tzafrirben/babashka-docker-action@v1.1
        id: create_uberscript
        with:
          bb_cmd: |
            mkdir -p dist
            bb -e "(require '[babashka.fs :as fs] '[babashka.process :as p]) 
                   (let [tmp-file \"hook-smith.clj\"] 
                     (p/shell \"bb\" \"uberscript\" tmp-file \"hook\") 
                     (fs/copy tmp-file \"dist/hook-smith\") 
                     (p/shell \"chmod\" \"+x\" \"dist/hook-smith\"))"
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set version for manual run
        run: echo "VERSION=latest" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          name: Hook Smith ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/hook-smith
            LICENSE
            README.md